# 服务器配置
server:
  mode: "debug" # 可选值: debug, release
  port: 8080

# 数据库配置
database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  dbname: "hserp"
  dialect: "mysql"

# 日志配置，严格大小写
log:
  level: "Info" # 日志级别:  Error, Warn, Info
  access: true # 是记录访问日志
  level_sql: "Info" # SQL日志级别: Silent, Error, Warn, Info
  dir: "./logs" # 日志保存目录


# JWT配置
jwt:
  secret: "webgos_secret_key"
  expiry: 24 # 小时

# 自动迁移配置 (默认为false)
auto_migrate: false
# 自动同步RBAC权限点 (默认为false)
auto_rbac_point: false
# 超级管理员账号
super_account: "super"